# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  name: DOCKER_REPOSITORY

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
        
        
    
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'aws-fix-it'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: 'fix-it-backend-pub'
        repositoryName: 'fixitcentral2021/fix-it-backend-pub_api'
        autoCreateRepository: true
        logRequest: true
        logResponse: true
