--- 
phases:
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "sudo docker login --username=\"fixitcentral2021\" --password=\"virtualizaci0n.2021\""
  build: 
    commands: 
      - "echo Building the Docker image..."
      - "sudo docker build -t fixitcentral2021/fix-it-backend-pub_api ."
      - "sudo docker tag dvohra/node-server fixitcentral2021/fix-it-backend-pub_api:latest"
  post_build: 
    commands: 
      - "echo Build completed"
      - "echo Pushing the Docker image..."
      - "sudo docker push fixitcentral2021/fix-it-backend-pub_api:latest"
version: 0.1
